### ISSUE TITLE
Cooperation

### ISSUE THREAD

**Issue by Bost** [AtilioA/COVID19NowBot#4]
A day or two ago I discovered your bot. Nice work! It looks a bit like mine https://t.me/corona_cases_bot which is, hmm, interesting :)

So yeah, would you be interested in some sort of cooperation? I see yours is in JavaScript while mine is in Clojure but maybe we can at least exchange some ideas, share experiences etc. What do you think?

**Comment by AtilioA** [comment]
Hello! So, "for the record", my inspiration was @CoronaNowBot (not open-source, not sure if it's still active). The similarities are obvious.

> mine is in Clojure but maybe we can at least exchange some ideas, share experiences etc. What do you think?

Unfortunately, I've never fiddled with Clojure, but yeah, feel free to message me on Telegram (see my profile README).
